language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15
# 20201215: compilation failure on
#  - openjdk16

addons:
  apt:
    packages:
    - xvfb
    - vnc-java
    - x11vnc
    - tightvncserver
env:
  - DSPLAY=:0
before_script:
  - pip install --user codecov

after_success:
  - codecov

#addons:
#  srcclr: true
